version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: meu-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: seu_usuario
      MONGO_INITDB_ROOT_PASSWORD: sua_senha
    volumes:
      - ./data:/data/db