apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-production-volume
  namespace: mongo
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db"
