apiVersion: apps/v1
kind: Deployment
metadata:
  name: foursix-production-deployment
  labels:
    app: foursix-production-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foursix-production-deployment
  template:
    metadata:
      labels:
        app: foursix-production-deployment
    spec:
      containers:
      - name: c-foursix-deployment # what?
        image: manojs10/java-four-six:latest
        ports:
        - containerPort: 30030
