apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-production-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-production-deployment
  template:
    metadata:
      labels:
        app: mongo-production-deployment
    spec:
      containers:
        - name: mongo-production-deployment
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: teste
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: teste
      volumes:
        - name: mongo-data
          emptyDir: {}
      initContainers:
        - name: init-mongo-user
          image: mongo:latest
          command: [ "bash", "-c", "mongo --host localhost --port 27017 --eval 
          'db.createUser({user: \"teste\", pwd: \"teste\", roles: [{role: \"readWrite\", db: \"teste\"}]})'" ]