apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-production-service
  name: mongo-production-service
spec:
  selector:
    app: mongo-production-deployment
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  type: LoadBalancer
